# Generated by Django 4.2.7 on 2023-12-04 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_rename_customer_dealer'),
    ]

    operations = [
        migrations.AddField(
            model_name='dealer',
            name='password',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
