# Generated by Django 4.2.7 on 2023-12-07 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_remove_dealer_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shipping_Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=50, null=True)),
            ],
            options={
                'verbose_name_plural': 'Shipping Status',
            },
        ),
    ]
