# Generated by Django 4.2.7 on 2023-12-07 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_shipping_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shippingaddress',
            options={'verbose_name_plural': 'Shipping Addresses'},
        ),
    ]
