# Generated by Django 4.2.7 on 2023-12-07 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_alter_shippingaddress_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Shipping_Status',
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_status',
            field=models.CharField(choices=[('placed', 'Order Placed'), ('out_for_delivery', 'Out for Delivery'), ('delivered', 'Delivered')], default='placed', max_length=50),
        ),
    ]
