# Generated by Django 4.2.7 on 2023-12-23 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0017_alter_order_shipping_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='dealer',
            name='user_type',
            field=models.CharField(choices=[('admin', 'Admin'), ('manager', 'Manager'), ('staff', 'Staff'), ('dealer', 'Dealer')], max_length=50, null=True),
        ),
    ]
