# Generated by Django 4.2.7 on 2024-01-03 17:57

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0019_dealer_number'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Dealer',
            new_name='Customer',
        ),
    ]
