# Generated by Django 4.2.7 on 2024-01-11 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0021_alter_customer_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='urgent',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
