# Generated by Django 4.2.7 on 2024-01-12 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0022_order_urgent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='shipping_status',
            field=models.CharField(choices=[('pending', 'Order Pending'), ('accepted', 'Order Accepted'), ('processing', 'Processing'), ('dispatched', 'Dispatched'), ('delivered', 'Delivered')], default='pending', max_length=50),
        ),
    ]
