# Generated by Django 4.2.7 on 2024-01-30 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0023_alter_order_shipping_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='dispatched_quantity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('dispatched', 'Dispatched')], default='pending', max_length=50),
        ),
        migrations.DeleteModel(
            name='ShippingAddress',
        ),
    ]
