# Generated by Django 4.2.7 on 2024-02-13 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0025_remove_product_digital_product_inventory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='user_type',
            field=models.CharField(choices=[('admin', 'Admin'), ('manager', 'Manager'), ('staff', 'Staff'), ('customer', 'Customer'), ('customer2', 'Customer Type 2')], max_length=50, null=True),
        ),
    ]
