# Generated by Django 4.2.7 on 2024-02-15 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0031_customer_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='user_type',
            field=models.CharField(choices=[('admin', 'Admin'), ('manager', 'Manager'), ('staff', 'Staff'), ('customer', 'Red Poly Dealer'), ('altcustomer', 'Normal Dealer')], max_length=50, null=True),
        ),
    ]
