# Generated by Django 4.2.7 on 2024-02-24 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0033_alter_customer_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='redpoly',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='no', max_length=50),
        ),
        migrations.AlterField(
            model_name='customer',
            name='user_type',
            field=models.CharField(choices=[('admin', 'Admin'), ('manager', 'Manager'), ('customer', 'Dealer')], max_length=50, null=True),
        ),
    ]
