# Generated by Django 4.2.7 on 2024-02-24 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0036_price_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='price',
            name='name',
        ),
    ]
