# Generated by Django 4.2.7 on 2024-02-24 06:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0037_remove_price_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='base_price',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_price', to='store.price'),
        ),
    ]
