# Generated by Django 4.2.7 on 2024-02-28 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0040_alter_product_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='base_price',
        ),
        migrations.AddField(
            model_name='price',
            name='name',
            field=models.CharField(db_index=True, max_length=255, null=True),
        ),
    ]
