# Generated by Django 4.2.7 on 2024-03-02 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0041_remove_product_base_price_price_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cancellation_approved',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='cancellation_requested',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
