# Generated by Django 4.2.7 on 2024-03-12 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0043_order_cancellation_denied'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='slug',
        ),
    ]
