# Generated by Django 4.2.7 on 2024-03-15 05:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0045_orderitem_urgent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='urgent',
        ),
        migrations.CreateModel(
            name='OrderedProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pending_quantity', models.IntegerField(default=0)),
                ('dispatched_quantity', models.IntegerField(default=0)),
                ('urgent', models.BooleanField(default=False)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.customer')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.product')),
            ],
        ),
    ]
