# Generated by Django 4.2.7 on 2024-03-17 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0047_delete_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderedproduct',
            name='status',
            field=models.CharField(choices=[('placed', 'Placed'), ('cancel-requested', 'Cancellation Requested'), ('cancel-approved', 'Cancellation Approved'), ('cancel-denied', 'Cancellation Denied')], default='placed', max_length=50),
        ),
    ]
