# Generated by Django 4.2.7 on 2024-03-25 08:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0048_orderedproduct_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderedproduct',
            name='date_ordered',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
